### PR TITLE
Login sign up

### PR DESCRIPTION
**Pull request by Aaron-Mandela-Okullo**

### CODE REVIEW

**Comment by fatuma65** [comment]
Hi Aaron, this branch has conflicts that need to be solved before merging

**Comment by Aaron-Mandela-Okullo** [comment]
Are you free after the call and we go over it?

**Comment by fatuma65** [comment]
Yes please

**Comment by Aaron-Mandela-Okullo** [comment]
ok we can jump in after the call

**Comment by Aaron-Mandela-Okullo** [comment]
I have power now co we proceed, please

**Pull request closed without merging**
