### PR TITLE
create trending products section and single product page

### PR DESCRIPTION
**Pull request by fatuma65**
I have created trending products page.
Implemented single product page
implemented related products functionality

### CODE REVIEW

**Comment by FREDVUNI** [comment]
@fatuma65, This PR has conflicts

**Comment by fatuma65** [comment]
@FREDVUNI I have solved the conflicts successfully and pushed the changes

**Comment by FREDVUNI** [comment]
I still see conflicts

image

**Comment by fatuma65** [comment]
I am done solving the conflicts.

**Comment by FREDVUNI** [comment]
looks good

**Pull request merged**
